version: "3.8"

services:
  alloy-api:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 22.16.0
    container_name: alloy-api
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://alloy:alloy@alloy-database:5432/alloy
    ports:
      - "3000:3000"
    depends_on:
      alloy-database:
        condition: service_healthy

  alloy-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: alloy-client
    ports:
      - "3001:80"
    environment:
      VITE_API_URL: http://alloy-api:3000
    depends_on:
      - alloy-api

  alloy-database:
    image: postgres:15-alpine
    container_name: alloy-database
    restart: always
    environment:
      POSTGRES_DB: alloy
      POSTGRES_USER: alloy
      POSTGRES_PASSWORD: alloy
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./server/migrations:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5

volumes:
  db-data:
